[db]
port = 54332

[auth]
site_url = "http://localhost:8787"
additional_redirect_urls = [
  "http://localhost:5173/auth/callback",
  "http://localhost:8787/auth/callback",
  "https://aula-base.prroyectoeducativo00.workers.dev/auth/callback",
  "https://aula-base-staging.prroyectoeducativo00.workers.dev/auth/callback",
]

[auth.email]
enable_confirmations = false
