-- Canonical schema lives in formal Supabase migrations.
-- Current initial migration:
--   supabase/migrations/001_initial_student_system_schema.sql
--
-- Keep this file as a pointer only. Do not apply it directly.
