export const DB_ERROR = {
  UNIQUE_VIOLATION: '23505',
  PERMISSION_DENIED: '42501',
} as const

export const THRESHOLD = {
  ATTENDANCE_LOW: 70,
  ATTENDANCE_WARNING: 80,
  ATTENDANCE_ALERT: 75,
  GRADE_LOW: 6.5,
  GRADE_WARNING: 7.5,
  PERFORMANCE_LOW: 70,
} as const

export const ALERT = {
  PERFORMANCE_HIGH: 10,
  ATTENDANCE_HIGH: 15,
  RECOVERY_HIGH: 5,
} as const

export const DEFAULTS = {
  IMPORT_BATCH_SIZE: 50,
  MAX_WEEKLY_HOURS: 40,
  RECENT_DAYS: 30,
  RECENT_DAYS_ATTENDANCE_CHART: 28,
  PREVIEW_MAX_ROWS: 10,
  AUTH_EVENT_TIMEOUT_MS: 750,
  HOUR_HEIGHT_REM: 7.25,
  VISIBLE_START_HOUR: 8,
  VISIBLE_HOUR_COUNT: 9,
  MIN_ENTRY_HEIGHT_REM: 5.25,
} as const
