import { Check, ChevronLeft, ChevronRight, Clock3, Coffee, MoreVertical, Pencil, Plus, RotateCcw, Trash2 } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Button } from '@/components/ui/Button'
import { ConfirmDialog } from '@/components/ui/ConfirmDialog'
import { Input } from '@/components/ui/Input'
import { Modal } from '@/components/ui/Modal'
import { Select } from '@/components/ui/Select'
import { FeedbackBanner } from '@/components/ui/SemanticUI'
import type { SaveScheduleStructureInput, ScheduleBlockType, ScheduleJourneyKind, ScheduleStructureJourneyInput, TimeSlot } from '@/modules/schedule/types'
import { blockTypeLabels, generateTemplateBlocks, insertTemplateBreak, materializeJourneyDraft, minutesFromScheduleTime, scheduleDays, summarizeBlocks, templateFromDay, type JourneyStructureDraft, type ScheduleTemplateBlock } from '@/modules/schedule/utils/scheduleStructure'
import { cn } from '@/utils/cn'

const steps = ['Días', 'Jornadas', 'Períodos', 'Clases']
const presets: Array<{ kind: ScheduleJourneyKind; name: string; start: string; end: string }> = [
  { kind: 'MORNING', name: 'Matutina', start: '07:30', end: '12:00' },
  { kind: 'AFTERNOON', name: 'Vespertina', start: '13:00', end: '17:00' },
  { kind: 'NIGHT', name: 'Nocturna', start: '18:00', end: '22:00' },
  { kind: 'EXTENDED', name: 'Jornada extendida', start: '08:00', end: '16:00' },
  { kind: 'CUSTOM', name: 'Personalizada', start: '08:00', end: '12:00' },
]

type WizardSummary = { days: number; journeys: number; periods: number; lectiveMinutes: number }
type CellEditorDraft = { journeyId: string; dayOfWeek: number; sequence: number; block: ScheduleTemplateBlock; error: string | null }
type Props = { initialJourneys?: ScheduleStructureJourneyInput[]; initialSlots?: TimeSlot[]; submitting: boolean; error: string | null; onComplete: (input: SaveScheduleStructureInput) => void; onCancel?: () => void; onSummaryChange?: (summary: WizardSummary) => void }

function newJourneyId() { return crypto.randomUUID() }
function emptyDraft(days: number[]): JourneyStructureDraft { return { durationMinutes: 40, periodCount: 6, appliedDays: [...days], baseBlocks: [], dayOverrides: {} } }

export function FlexibleScheduleWizard({ initialJourneys = [], initialSlots = [], submitting, error, onComplete, onCancel, onSummaryChange }: Props) {
  const inferredDays = [...new Set(initialSlots.map((slot) => slot.dayOfWeek).filter((day): day is number => typeof day === 'number' && day >= 1 && day <= 7))]
  const [step, setStep] = useState(0)
  const [days, setDays] = useState<number[]>(inferredDays.length ? inferredDays : [1, 2, 3, 4, 5])
  const [journeys, setJourneys] = useState<ScheduleStructureJourneyInput[]>(initialJourneys)
  const [drafts, setDrafts] = useState<Record<string, JourneyStructureDraft>>(() => Object.fromEntries(initialJourneys.map((journey) => {
    const journeyDays = [...new Set(initialSlots.filter((slot) => slot.journeyId === journey.id && typeof slot.dayOfWeek === 'number').map((slot) => slot.dayOfWeek!))]
    const appliedDays = journeyDays.length ? journeyDays : inferredDays
    const firstDay = appliedDays[0]
    const baseBlocks = firstDay ? templateFromDay(journey.id, firstDay, initialSlots) : []
    const dayOverrides = Object.fromEntries(appliedDays.filter((day) => JSON.stringify(templateFromDay(journey.id, day, initialSlots).map(withoutIdentity)) !== JSON.stringify(baseBlocks.map(withoutIdentity))).map((day) => [day, templateFromDay(journey.id, day, initialSlots)]))
    return [journey.id, { ...emptyDraft(appliedDays), periodCount: baseBlocks.filter((block) => block.blockType === 'CLASS').length || 6, baseBlocks, dayOverrides }]
  })))
  const [confirm, setConfirm] = useState<{ journeyId: string; action: 'clear' | 'regenerate' } | null>(null)
  const [cellEditor, setCellEditor] = useState<CellEditorDraft | null>(null)

  const materialized = useMemo(() => journeys.flatMap((journey) => drafts[journey.id] ? materializeJourneyDraft(journey.id, drafts[journey.id], initialSlots) : []), [drafts, initialSlots, journeys])
  const summary = useMemo<WizardSummary>(() => ({ days: days.length, journeys: journeys.length, periods: materialized.filter((block) => block.blockType === 'CLASS').length, lectiveMinutes: summarizeBlocks(materialized).class }), [days.length, journeys.length, materialized])
  useEffect(() => { onSummaryChange?.(summary) }, [onSummaryChange, summary])

  function toggleDay(day: number) { setDays((current) => current.includes(day) ? current.filter((item) => item !== day) : [...current, day].sort()) }
  function addJourney(preset: typeof presets[number]) {
    if (preset.kind !== 'CUSTOM' && journeys.some((journey) => journey.kind === preset.kind)) return
    const id = newJourneyId()
    setJourneys((current) => [...current, { id, name: preset.kind === 'CUSTOM' ? 'Mi jornada' : preset.name, kind: preset.kind, startTime: preset.start, endTime: preset.end, sequence: current.length + 1 }])
    setDrafts((current) => ({ ...current, [id]: emptyDraft(days) }))
  }
  function updateJourney(id: string, patch: Partial<ScheduleStructureJourneyInput>) { setJourneys((current) => current.map((journey) => journey.id === id ? { ...journey, ...patch } : journey)) }
  function removeJourney(id: string) { setJourneys((current) => current.filter((journey) => journey.id !== id).map((journey, index) => ({ ...journey, sequence: index + 1 }))); setDrafts((current) => { const next = { ...current }; delete next[id]; return next }) }
  function updateDraft(id: string, patch: Partial<JourneyStructureDraft>) { setDrafts((current) => ({ ...current, [id]: { ...current[id], ...patch } })) }
  function generate(id: string) { const journey = journeys.find((item) => item.id === id)!; const draft = drafts[id]; updateDraft(id, { baseBlocks: generateTemplateBlocks(journey.startTime, draft.durationMinutes, draft.periodCount), dayOverrides: {} }) }
  function addPeriod(id: string) { const journey = journeys.find((item) => item.id === id)!; const draft = drafts[id]; const last = draft.baseBlocks.at(-1); const generated = generateTemplateBlocks(last?.endTime ?? journey.startTime, draft.durationMinutes, 1)[0]; const added = { ...generated, name: `Período ${draft.baseBlocks.filter((block) => block.blockType === 'CLASS').length + 1}` }; const append = (blocks: ScheduleTemplateBlock[]) => [...blocks, { ...added, key: crypto.randomUUID(), sequence: blocks.length + 1 }]; updateDraft(id, { baseBlocks: append(draft.baseBlocks), dayOverrides: Object.fromEntries(Object.entries(draft.dayOverrides).map(([day, blocks]) => [day, append(blocks)])) }) }
  function addBreak(id: string) { const draft = drafts[id]; if (!draft.baseBlocks.length) return; const insert = (blocks: ScheduleTemplateBlock[]) => insertTemplateBreak(blocks, Math.min(2, blocks.length - 1), 30, 'Recreo', true); updateDraft(id, { baseBlocks: insert(draft.baseBlocks), dayOverrides: Object.fromEntries(Object.entries(draft.dayOverrides).map(([day, blocks]) => [day, insert(blocks)])) }) }
  function openCellEditor(id: string, day: number, block: ScheduleTemplateBlock) { setCellEditor({ journeyId: id, dayOfWeek: day, sequence: block.sequence, block: { ...block }, error: null }) }
  function effectiveBlocks(id: string, day: number) { const draft = drafts[id]; return draft.dayOverrides[day] ?? draft.baseBlocks }
  function setDayBlocks(id: string, day: number, blocks: ScheduleTemplateBlock[]) { const draft = drafts[id]; updateDraft(id, { dayOverrides: { ...draft.dayOverrides, [day]: blocks.map((block, index) => ({ ...block, sequence: index + 1 })) } }) }
  function deleteCell(id: string, day: number, sequence: number) { setDayBlocks(id, day, effectiveBlocks(id, day).filter((block) => block.sequence !== sequence)) }
  function restoreDay(id: string, day: number) { const draft = drafts[id]; const dayOverrides = { ...draft.dayOverrides }; delete dayOverrides[day]; updateDraft(id, { dayOverrides }) }
  function saveCellEditor() { if (!cellEditor) return; const journey = journeys.find((item) => item.id === cellEditor.journeyId)!; const blocks = effectiveBlocks(cellEditor.journeyId, cellEditor.dayOfWeek).map((block) => block.sequence === cellEditor.sequence ? cellEditor.block : block); const errors = validateBlocks(journey, blocks); if (errors.length) { setCellEditor({ ...cellEditor, error: errors[0] }); return } setDayBlocks(cellEditor.journeyId, cellEditor.dayOfWeek, blocks); setCellEditor(null) }
  function confirmAction() { if (!confirm) return; if (confirm.action === 'clear') updateDraft(confirm.journeyId, { baseBlocks: [], dayOverrides: {} }); else generate(confirm.journeyId); setConfirm(null) }

  const structureErrors = journeys.flatMap((journey) => validateTemplate(journey, drafts[journey.id]))
  const canContinue = step === 0 ? days.length > 0 : step === 1 ? journeys.length > 0 : step === 2 ? materialized.some((block) => block.blockType === 'CLASS') && structureErrors.length === 0 : structureErrors.length === 0
  function next() { if (step < 3) setStep((value) => value + 1); else onComplete({ journeys, blocks: materialized }) }

  return <section className="overflow-hidden rounded-3xl bg-card shadow-sm">
    <header className="border-b border-border px-5 py-5 sm:px-7"><p className="text-xs font-bold text-muted-foreground sm:hidden">Paso {step + 1} de 4 · {steps[step]}</p><div className="mt-2 grid grid-cols-4 gap-2" aria-label="Progreso de configuración">{steps.map((label, index) => <button key={label} type="button" disabled={index > step} onClick={() => index < step && setStep(index)} className={cn('flex min-w-0 items-center gap-2 rounded-xl px-2 py-2 text-left text-xs font-bold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring', index === step ? 'bg-primary/10 text-primary' : index < step ? 'text-foreground' : 'text-muted-foreground')}><span className={cn('grid size-7 shrink-0 place-items-center rounded-full', index <= step ? 'bg-primary text-primary-foreground' : 'bg-muted')}>{index < step ? <Check className="size-4" /> : index + 1}</span><span className="hidden truncate sm:block">{label}</span></button>)}</div></header>
    <div className="space-y-6 p-5 sm:p-7">
      {error ? <FeedbackBanner tone="danger">No pudimos guardar la estructura del horario. Revisa tu conexión y vuelve a intentarlo.</FeedbackBanner> : null}
      {step === 0 ? <DaysStep days={days} toggleDay={toggleDay} /> : null}
      {step === 1 ? <JourneysStep journeys={journeys} addJourney={addJourney} updateJourney={updateJourney} removeJourney={removeJourney} /> : null}
      {step === 2 ? <><Heading title="¿Cómo se distribuye el tiempo?" description="Genera la estructura habitual de cada jornada y ajusta cualquier día directamente en el horario." />{journeys.map((journey) => <JourneyPeriods key={journey.id} journey={journey} draft={drafts[journey.id]} selectedDays={days} onDraft={updateDraft} onGenerate={(id) => drafts[id].baseBlocks.length ? setConfirm({ journeyId: id, action: 'regenerate' }) : generate(id)} onAddPeriod={addPeriod} onAddBreak={addBreak} onClear={(id) => setConfirm({ journeyId: id, action: 'clear' })} onEditCell={openCellEditor} onDeleteCell={deleteCell} onRestoreDay={restoreDay} />)}{structureErrors.length ? <FeedbackBanner tone="danger"><ul className="list-disc pl-5">{structureErrors.map((message) => <li key={message}>{message}</li>)}</ul></FeedbackBanner> : null}</> : null}
      {step === 3 ? <><Heading title="Asigna tus clases" description="Selecciona qué curso y asignatura corresponde a cada período lectivo." /><div className="grid gap-3 sm:grid-cols-4"><Summary label="Días" value={summary.days} /><Summary label="Jornadas" value={summary.journeys} /><Summary label="Períodos" value={summary.periods} /><Summary label="Tiempo lectivo" value={`${Math.floor(summary.lectiveMinutes / 60)} h ${summary.lectiveMinutes % 60} min`} /></div><p className="rounded-2xl bg-primary/5 p-4 text-sm text-muted-foreground">Al continuar guardaremos la estructura y abriremos la vista semanal para asignar las clases.</p></> : null}
    </div>
    <footer className="flex items-center justify-between border-t border-border px-5 py-4 sm:px-7"><div>{step > 0 ? <Button type="button" variant="ghost" onClick={() => setStep((value) => value - 1)}><ChevronLeft className="size-4" />Atrás</Button> : onCancel ? <Button type="button" variant="ghost" onClick={onCancel}>Cancelar</Button> : null}</div><Button type="button" disabled={!canContinue || submitting} loading={submitting} onClick={next}>{step === 3 ? 'Guardar y asignar clases' : 'Continuar'}{step < 3 ? <ChevronRight className="size-4" /> : null}</Button></footer>
    {confirm ? <ConfirmDialog title={confirm.action === 'clear' ? 'Limpiar jornada' : 'Regenerar jornada'} description={confirm.action === 'clear' ? 'Se eliminarán todos los períodos y recreos de esta jornada.' : 'Se reemplazará el horario de todos los días de esta jornada, incluidos sus ajustes manuales.'} confirmLabel={confirm.action === 'clear' ? 'Limpiar' : 'Regenerar'} destructive={confirm.action === 'clear'} onConfirm={confirmAction} onClose={() => setConfirm(null)} /> : null}
    {cellEditor ? <Modal title={`${scheduleDays.find((day) => day.dayOfWeek === cellEditor.dayOfWeek)?.name} · Editar bloque`} description="Este cambio se aplicará únicamente a este día." icon={Pencil} tone="info" className="max-w-xl" onClose={() => setCellEditor(null)}><div className="space-y-4 p-5"><div className="grid gap-3 sm:grid-cols-2"><Field label="Tipo"><Select value={cellEditor.block.blockType} onChange={(event) => setCellEditor({ ...cellEditor, error: null, block: { ...cellEditor.block, blockType: event.target.value as ScheduleBlockType } })}>{Object.entries(blockTypeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select></Field><Field label="Nombre"><Input value={cellEditor.block.name} onChange={(event) => setCellEditor({ ...cellEditor, error: null, block: { ...cellEditor.block, name: event.target.value } })} /></Field><Field label="Inicio"><Input type="time" value={cellEditor.block.startTime} onChange={(event) => setCellEditor({ ...cellEditor, error: null, block: { ...cellEditor.block, startTime: event.target.value } })} /></Field><Field label="Fin"><Input type="time" value={cellEditor.block.endTime} onChange={(event) => setCellEditor({ ...cellEditor, error: null, block: { ...cellEditor.block, endTime: event.target.value } })} /></Field></div>{cellEditor.error ? <p role="alert" className="text-xs font-semibold text-destructive">{cellEditor.error}</p> : null}<div className="flex justify-end gap-2"><Button type="button" variant="ghost" onClick={() => setCellEditor(null)}>Cancelar</Button><Button type="button" onClick={saveCellEditor}>Guardar cambios</Button></div></div></Modal> : null}
  </section>
}

function DaysStep({ days, toggleDay }: { days: number[]; toggleDay: (day: number) => void }) { return <><Heading title="¿Qué días impartes clases?" description="Selecciona los días en los que normalmente impartes clases." /><div className="grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-7">{scheduleDays.map((day) => { const selected = days.includes(day.dayOfWeek); return <button key={day.dayOfWeek} type="button" aria-pressed={selected} onClick={() => toggleDay(day.dayOfWeek)} className={cn('min-h-20 rounded-2xl border px-3 py-4 text-center font-bold transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring', selected ? 'border-primary bg-primary/10 text-primary' : 'border-border text-muted-foreground hover:border-primary/30')}><span className="block text-lg">{day.short}</span><span className="mt-1 block text-xs">{day.name}</span></button> })}</div></> }

function JourneysStep({ journeys, addJourney, updateJourney, removeJourney }: { journeys: ScheduleStructureJourneyInput[]; addJourney: (preset: typeof presets[number]) => void; updateJourney: (id: string, patch: Partial<ScheduleStructureJourneyInput>) => void; removeJourney: (id: string) => void }) { return <><Heading title="¿En qué jornadas trabajas?" description="Selecciona una o varias jornadas y ajusta sus horarios al funcionamiento real de tu centro." /><p className="text-xs font-semibold text-muted-foreground">Puedes seleccionar más de una. Los horarios son sugeridos y siempre puedes modificarlos.</p><div className="flex flex-wrap gap-2">{presets.map((preset) => { const selected = preset.kind !== 'CUSTOM' && journeys.some((journey) => journey.kind === preset.kind); return <Button key={preset.kind} type="button" variant={selected ? 'secondary' : 'outline'} disabled={selected} onClick={() => addJourney(preset)}>{selected ? <Check className="size-4" /> : <Plus className="size-4" />}{preset.name}</Button> })}</div><div className="space-y-3">{journeys.map((journey) => <article key={journey.id} className="rounded-2xl border border-border p-4"><div className="flex items-start justify-between gap-3"><div>{journey.kind === 'CUSTOM' ? <label className="space-y-1"><span className="text-xs font-bold text-muted-foreground">Nombre de la jornada</span><Input value={journey.name} onChange={(event) => updateJourney(journey.id, { name: event.target.value })} /></label> : <><h4 className="text-sm font-black uppercase tracking-wide">{journey.name}</h4><p className="mt-1 text-xs text-muted-foreground">Horario sugerido. Puedes modificarlo.</p></>}</div><Button type="button" variant="ghost" size="sm" className="text-destructive" onClick={() => removeJourney(journey.id)}><Trash2 className="size-4" />Eliminar</Button></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="Inicio"><Input type="time" value={journey.startTime} onChange={(event) => updateJourney(journey.id, { startTime: event.target.value })} /></Field><Field label="Fin"><Input type="time" value={journey.endTime} onChange={(event) => updateJourney(journey.id, { endTime: event.target.value })} /></Field></div></article>)}</div></> }

function JourneyPeriods({ journey, draft, selectedDays, onDraft, onGenerate, onAddPeriod, onAddBreak, onClear, onEditCell, onDeleteCell, onRestoreDay }: { journey: ScheduleStructureJourneyInput; draft: JourneyStructureDraft; selectedDays: number[]; onDraft: (id: string, patch: Partial<JourneyStructureDraft>) => void; onGenerate: (id: string) => void; onAddPeriod: (id: string) => void; onAddBreak: (id: string) => void; onClear: (id: string) => void; onEditCell: (id: string, day: number, block: ScheduleTemplateBlock) => void; onDeleteCell: (id: string, day: number, sequence: number) => void; onRestoreDay: (id: string, day: number) => void }) {
  useEffect(() => { if (draft.appliedDays.length !== selectedDays.length || selectedDays.some((day) => !draft.appliedDays.includes(day))) onDraft(journey.id, { appliedDays: [...selectedDays] }) }, [draft.appliedDays, journey.id, onDraft, selectedDays])
  return <section className="space-y-4 rounded-2xl border border-border p-4 sm:p-5"><div><h4 className="font-black uppercase tracking-wide">{journey.name}</h4><p className="text-xs text-muted-foreground">{journey.startTime} – {journey.endTime}</p></div><div className="grid gap-3 rounded-2xl bg-muted/30 p-4 sm:grid-cols-[13rem_10rem_auto]"><Field label="Duración base de cada clase"><div className="relative"><Input type="number" min={5} value={draft.durationMinutes} onChange={(event) => onDraft(journey.id, { durationMinutes: Math.max(5, Number(event.target.value)) })} /><span className="pointer-events-none absolute right-3 top-3 text-xs text-muted-foreground">minutos</span></div></Field><Field label="Número de períodos"><Input type="number" min={1} value={draft.periodCount} onChange={(event) => onDraft(journey.id, { periodCount: Math.max(1, Number(event.target.value)) })} /></Field><div className="flex items-end"><Button type="button" onClick={() => onGenerate(journey.id)}><RotateCcw className="size-4" />Generar estructura</Button></div></div>{draft.baseBlocks.length ? <><div className="flex flex-wrap gap-2"><Button type="button" size="sm" variant="outline" onClick={() => onAddPeriod(journey.id)}><Plus className="size-4" />Añadir período</Button><Button type="button" size="sm" variant="outline" onClick={() => onAddBreak(journey.id)}><Coffee className="size-4" />Añadir recreo</Button><Button type="button" size="sm" variant="outline" onClick={() => onGenerate(journey.id)}><RotateCcw className="size-4" />Regenerar</Button><Button type="button" size="sm" variant="ghost" className="text-destructive" onClick={() => onClear(journey.id)}><Trash2 className="size-4" />Limpiar jornada</Button></div><WeeklyPeriodGrid journey={journey} draft={draft} days={selectedDays} onEdit={onEditCell} onDelete={onDeleteCell} onRestore={onRestoreDay} /></> : <div className="rounded-2xl border border-dashed border-border py-8 text-center"><Clock3 className="mx-auto size-7 text-muted-foreground" /><p className="mt-2 text-sm font-bold">Genera la estructura para ver el horario semanal de esta jornada.</p></div>}</section>
}

function WeeklyPeriodGrid({ journey, draft, days, onEdit, onDelete, onRestore }: { journey: ScheduleStructureJourneyInput; draft: JourneyStructureDraft; days: number[]; onEdit: (id: string, day: number, block: ScheduleTemplateBlock) => void; onDelete: (id: string, day: number, sequence: number) => void; onRestore: (id: string, day: number) => void }) {
  const [mobileDay, setMobileDay] = useState(days[0] ?? 1)
  const blocksFor = (day: number) => draft.dayOverrides[day] ?? draft.baseBlocks
  const rows = [...new Set(days.flatMap((day) => blocksFor(day).map((block) => `${block.startTime}|${block.endTime}`)))].sort()
  const cell = (day: number, row: string) => { const [startTime, endTime] = row.split('|'); const block = blocksFor(day).find((item) => item.startTime === startTime && item.endTime === endTime); if (!block) return <span className="text-muted-foreground">—</span>; const adjusted = Boolean(draft.dayOverrides[day]); return <div className={cn('group relative min-h-16 rounded-xl border p-2 text-left', block.blockType === 'BREAK' ? 'border-warning/30 bg-warning/15' : 'border-border bg-card')}><p className="pr-6 text-xs font-extrabold text-foreground">{block.name}</p><p className="mt-1 text-[10px] tabular-nums text-muted-foreground">{block.startTime}–{block.endTime}</p>{adjusted ? <span className="mt-1 inline-block text-[9px] font-bold text-primary">● Ajustado</span> : null}<details className="absolute right-1 top-1"><summary aria-label={`Acciones de ${block.name} en ${scheduleDays.find((item) => item.dayOfWeek === day)?.name}`} className="grid size-7 cursor-pointer list-none place-items-center rounded-lg text-muted-foreground hover:bg-muted [&::-webkit-details-marker]:hidden"><MoreVertical className="size-4" /></summary><div className="absolute right-0 z-20 mt-1 w-44 rounded-xl border border-border bg-card p-1 shadow-xl"><button type="button" className="w-full rounded-lg px-3 py-2 text-left text-xs font-bold hover:bg-muted" onClick={() => onEdit(journey.id, day, block)}>Editar</button><button type="button" className="w-full rounded-lg px-3 py-2 text-left text-xs font-bold text-destructive hover:bg-destructive/10" onClick={() => onDelete(journey.id, day, block.sequence)}>Eliminar de este día</button></div></details></div> }
  return <div className="space-y-3"><div className="flex gap-2 overflow-x-auto md:hidden">{days.map((day) => <button key={day} type="button" onClick={() => setMobileDay(day)} className={cn('rounded-xl px-3 py-2 text-xs font-bold', mobileDay === day ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground')}>{scheduleDays.find((item) => item.dayOfWeek === day)?.short}</button>)}</div><div className="space-y-2 md:hidden">{blocksFor(mobileDay).map((block) => <div key={block.key}>{cell(mobileDay, `${block.startTime}|${block.endTime}`)}</div>)}{draft.dayOverrides[mobileDay] ? <Button type="button" size="sm" variant="ghost" onClick={() => onRestore(journey.id, mobileDay)}><RotateCcw className="size-3" />Restaurar horario habitual</Button> : null}</div><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[760px] border-separate border-spacing-1.5"><thead><tr><th className="w-24 px-2 text-left text-[10px] uppercase tracking-wide text-muted-foreground">Hora</th>{days.map((day) => <th key={day} className="px-2 text-center text-xs font-extrabold text-foreground">{scheduleDays.find((item) => item.dayOfWeek === day)?.short}{draft.dayOverrides[day] ? <button type="button" className="ml-2 text-[9px] font-bold text-primary" onClick={() => onRestore(journey.id, day)}>Restaurar</button> : null}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row}><td className="px-2 text-[10px] tabular-nums text-muted-foreground">{row.replace('|', '–')}</td>{days.map((day) => <td key={day} className="align-top">{cell(day, row)}</td>)}</tr>)}</tbody></table></div></div>
}

function validateBlocks(journey: ScheduleStructureJourneyInput, blocks: ScheduleTemplateBlock[], label = 'horario personalizado') { const errors: string[] = []; const ordered = [...blocks].sort((a, b) => a.startTime.localeCompare(b.startTime)); ordered.forEach((block) => { if (minutesFromScheduleTime(block.endTime) <= minutesFromScheduleTime(block.startTime)) errors.push(`${journey.name} · ${label}: ${block.name} debe terminar después de iniciar.`); if (minutesFromScheduleTime(block.startTime) < minutesFromScheduleTime(journey.startTime) || minutesFromScheduleTime(block.endTime) > minutesFromScheduleTime(journey.endTime)) errors.push(`${journey.name} · ${label}: ${block.name} queda fuera de la jornada.`) }); for (let index = 1; index < ordered.length; index += 1) if (minutesFromScheduleTime(ordered[index].startTime) < minutesFromScheduleTime(ordered[index - 1].endTime)) errors.push(`${journey.name} · ${label}: hay bloques solapados.`); return errors }
function validateTemplate(journey: ScheduleStructureJourneyInput, draft?: JourneyStructureDraft) { if (!draft) return [`${journey.name}: falta configuración.`]; const errors = validateBlocks(journey, draft.baseBlocks, 'estructura base'); Object.entries(draft.dayOverrides).forEach(([day, blocks]) => errors.push(...validateBlocks(journey, blocks, scheduleDays.find((item) => item.dayOfWeek === Number(day))?.name ?? day))); if (!draft.appliedDays.length) errors.push(`${journey.name}: aplica la estructura al menos a un día.`); return [...new Set(errors)] }
function withoutIdentity(block: ScheduleTemplateBlock) { return { name: block.name, startTime: block.startTime, endTime: block.endTime, sequence: block.sequence, blockType: block.blockType } }
function Heading({ title, description }: { title: string; description: string }) { return <div><h3 className="text-xl font-extrabold text-foreground">{title}</h3><p className="mt-1 text-sm text-muted-foreground">{description}</p></div> }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="space-y-1"><span className="text-xs font-bold text-muted-foreground">{label}</span>{children}</label> }
function Summary({ label, value }: { label: string; value: string | number }) { return <div className="rounded-2xl border border-border p-4"><p className="text-xs font-bold text-muted-foreground">{label}</p><p className="mt-1 text-xl font-black text-foreground">{value}</p></div> }
