import { useEffect, useState, type ReactNode } from 'react'
import { Archive, ArchiveRestore, ExternalLink, FileText, FolderOpen, Image, Link2, Loader2, Plus, Search, Trash2, Upload } from 'lucide-react'
import { Button } from '@/components/ui/Button'
import { Modal } from '@/components/ui/Modal'
import { api } from '@/services/apiClient'

type Resource = { id:string; kind:'FILE'|'LINK'|'EVIDENCE'; title:string; description:string; originalName?:string; mimeType?:string; sizeBytes:number; category:string; linkedActivities:number }
type Library = { items:Resource[]; usageBytes:number; limitBytes:number }
const MAX_BYTES=25*1024*1024
const bytes=(n:number)=>n?`${(n/1048576).toFixed(n>10485760?0:1)} MB`:'0 MB'
async function optimizeImage(file:File){if(!file.type.startsWith('image/')||file.type==='image/png'||file.size<1024*1024)return file;const bitmap=await createImageBitmap(file);const scale=Math.min(1,1920/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d')!.drawImage(bitmap,0,0,canvas.width,canvas.height);const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/webp',.82));bitmap.close();return blob&&blob.size<file.size?new File([blob],file.name.replace(/\.[^.]+$/,'.webp'),{type:'image/webp'}):file}

export function SubjectResourcesPanel({sectionSubjectId,courseLabel,subjectName}:{sectionSubjectId:string|null;courseLabel:string;subjectName:string}) {
 const [data,setData]=useState<Library>({items:[],usageBytes:0,limitBytes:524288000}),[area,setArea]=useState<'library'|'evidence'>('library'),[archived,setArchived]=useState(false),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[modal,setModal]=useState<'file'|'link'|null>(null)
 const load=async()=>{if(!sectionSubjectId)return;setLoading(true);setError('');try{setData(await api.get<Library>(`/resources?sectionSubjectId=${encodeURIComponent(sectionSubjectId)}&status=${archived?'archived':'active'}&kind=${area==='evidence'?'EVIDENCE':'ALL'}&q=${encodeURIComponent(q)}`,{forceRefresh:true}))}catch(e){setError(e instanceof Error?e.message:'No se pudieron cargar los recursos')}finally{setLoading(false)}}
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),200);return()=>window.clearTimeout(timer)},[sectionSubjectId,area,archived,q])
 const items=area==='library'?data.items.filter(i=>i.kind!=='EVIDENCE'):data.items
 if(!sectionSubjectId)return <p className="rounded-2xl bg-card p-6 text-sm text-muted-foreground">Esta asignatura todavía no está disponible.</p>
 return <section className="space-y-4"><header className="flex flex-col gap-4 rounded-2xl border border-border bg-card p-5 shadow-sm lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[.12em] text-primary">{courseLabel} · {subjectName}</p><h2 className="mt-1 text-2xl font-black text-foreground">Recursos y evidencias</h2><p className="mt-1 text-sm text-muted-foreground">Materiales privados y reutilizables de esta asignatura.</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>setModal('link')}><Link2 className="size-4"/>Agregar enlace</Button><Button onClick={()=>setModal('file')}><Upload className="size-4"/>Subir archivo</Button></div></header>
 <div className="grid gap-3 sm:grid-cols-3"><Metric label="Recursos activos" value={data.items.length}/><Metric label="Almacenamiento" value={`${bytes(data.usageBytes)} / ${bytes(data.limitBytes)}`}/><Metric label="Evidencias" value={data.items.filter(i=>i.kind==='EVIDENCE').length}/></div>
 <div className="flex flex-col gap-3 rounded-2xl border border-border bg-card p-3 shadow-sm lg:flex-row"><div className="flex rounded-xl bg-muted/40 p-1"><Tab active={area==='library'} onClick={()=>setArea('library')}>Biblioteca</Tab><Tab active={area==='evidence'} onClick={()=>setArea('evidence')}>Evidencias</Tab></div><label className="relative flex-1"><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><input className="h-10 w-full rounded-xl border border-border pl-9 pr-3 text-sm" placeholder="Buscar recursos…" value={q} onChange={e=>setQ(e.target.value)}/></label><Button variant="outline" onClick={()=>setArchived(v=>!v)}>{archived?<ArchiveRestore className="size-4"/>:<Archive className="size-4"/>}{archived?'Ver activos':'Archivados'}</Button></div>
 {error?<p className="rounded-xl bg-danger/10 p-4 text-sm font-semibold text-danger">{error}</p>:null}{loading?<div className="grid min-h-48 place-items-center"><Loader2 className="size-7 animate-spin text-primary"/></div>:items.length?<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{items.map(item=><Card key={item.id} item={item} archived={archived} reload={load}/>)}</div>:<div className="grid min-h-56 place-items-center rounded-2xl border border-dashed border-border bg-card text-center"><div><FolderOpen className="mx-auto size-10 text-primary"/><h3 className="mt-3 font-extrabold">{archived?'No hay recursos archivados':'Tu biblioteca está lista'}</h3><p className="text-sm text-muted-foreground">Sube un archivo o guarda un enlace para comenzar.</p></div></div>}
 {modal?<Form mode={modal} sectionSubjectId={sectionSubjectId} evidence={area==='evidence'} close={()=>setModal(null)} saved={()=>{setModal(null);void load()}}/>:null}</section>
}
function Tab({active,onClick,children}:{active:boolean;onClick:()=>void;children:string}){return <button className={`rounded-lg px-4 py-2 text-sm font-bold ${active?'bg-card text-primary shadow-sm':'text-muted-foreground'}`} onClick={onClick}>{children}</button>}
function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded-2xl border border-border bg-card p-4 shadow-sm"><p className="text-xs font-bold text-muted-foreground">{label}</p><p className="mt-1 text-xl font-black">{value}</p></div>}
function Card({item,archived,reload}:{item:Resource;archived:boolean;reload:()=>Promise<void>}){const act=async(action:string)=>{if(action==='delete'&&!confirm('¿Eliminar este recurso permanentemente?'))return;try{if(action==='delete')await api.delete(`/resources/${item.id}`);else await api.patch(`/resources/${item.id}/${action}`);await reload()}catch(e){alert(e instanceof Error?e.message:'No se pudo completar la acción')}};const Icon=item.kind==='LINK'?Link2:item.mimeType?.startsWith('image/')?Image:FileText;return <article className="flex min-h-44 flex-col rounded-2xl border border-border bg-card p-4 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex gap-3"><span className="grid size-11 place-items-center rounded-xl bg-primary/10 text-primary"><Icon className="size-5"/></span><div className="min-w-0 flex-1"><h3 className="truncate font-extrabold" title={item.title}>{item.title}</h3><p className="text-xs text-muted-foreground">{item.kind==='LINK'?'Enlace':bytes(item.sizeBytes)}</p></div></div><p className="mt-3 line-clamp-2 min-h-10 text-sm text-muted-foreground">{item.description||item.originalName||'Sin descripción'}</p><footer className="mt-auto flex items-center justify-between border-t border-border pt-3"><a className="flex items-center gap-1 text-sm font-bold text-primary" href={`/api/v1/resources/${item.id}/open`} target="_blank" rel="noreferrer">Abrir <ExternalLink className="size-4"/></a><div className="flex gap-1"><button className="grid size-8 place-items-center rounded-lg hover:bg-muted" title={archived?'Restaurar':'Archivar'} onClick={()=>void act(archived?'restore':'archive')}>{archived?<ArchiveRestore className="size-4"/>:<Archive className="size-4"/>}</button>{archived?<button className="grid size-8 place-items-center rounded-lg text-danger hover:bg-danger/10" title="Eliminar" onClick={()=>void act('delete')}><Trash2 className="size-4"/></button>:null}</div></footer></article>}
function Form({mode,sectionSubjectId,evidence,close,saved}:{mode:'file'|'link';sectionSubjectId:string;evidence:boolean;close:()=>void;saved:()=>void}){const [title,setTitle]=useState(''),[description,setDescription]=useState(''),[url,setUrl]=useState(''),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const submit=async()=>{if(!title.trim())return setError('Escribe un título');if(file&&file.size>MAX_BYTES)return setError('El archivo supera 25 MB');setBusy(true);try{if(mode==='link')await api.post('/resources/link',{sectionSubjectId,title,description,url,kind:evidence?'EVIDENCE':'LINK'});else{if(!file)throw new Error('Selecciona un archivo');const uploadFile=await optimizeImage(file);const form=new FormData();form.append('file',uploadFile);form.append('sectionSubjectId',sectionSubjectId);form.append('title',title);form.append('description',description);form.append('kind',evidence?'EVIDENCE':'FILE');const res=await fetch('/api/v1/resources/upload',{method:'POST',credentials:'include',body:form});const body=await res.json();if(!res.ok)throw new Error(body.error||body.message||'No se pudo subir')}saved()}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar')}finally{setBusy(false)}};return <Modal title={mode==='link'?'Agregar enlace':evidence?'Subir evidencia':'Subir recurso'} description="Solo estará disponible dentro de tu escuela." onClose={close}><div className="space-y-4"><Field label="Título"><input maxLength={160} className="h-11 w-full rounded-xl border border-border px-3" value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="Descripción"><textarea rows={3} maxLength={1000} className="w-full rounded-xl border border-border p-3" value={description} onChange={e=>setDescription(e.target.value)}/></Field>{mode==='link'?<Field label="Dirección web"><input type="url" className="h-11 w-full rounded-xl border border-border px-3" placeholder="https://…" value={url} onChange={e=>setUrl(e.target.value)}/></Field>:<label className="block cursor-pointer rounded-xl border border-dashed border-primary/40 bg-primary/5 p-5 text-center text-sm font-bold text-primary"><Upload className="mx-auto mb-2 size-6"/>{file?file.name:'Seleccionar archivo (máx. 25 MB)'}<input className="sr-only" type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.docx,.pptx,.xlsx,.txt" onChange={e=>setFile(e.target.files?.[0]??null)}/></label>}{error?<p className="rounded-xl bg-danger/10 p-3 text-sm text-danger">{error}</p>:null}<div className="flex justify-end gap-2"><Button variant="outline" onClick={close}>Cancelar</Button><Button disabled={busy} onClick={()=>void submit()}>{busy?<Loader2 className="size-4 animate-spin"/>:<Plus className="size-4"/>}Guardar</Button></div></div></Modal>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="block text-sm font-bold">{label}<span className="mt-1 block font-normal">{children}</span></label>}
